quarkus.datasource.db-kind=sqlite
quarkus.datasource.jdbc.url=jdbc:sqlite:lapis-mc.db
quarkus.rest-client.paper-api.url=https://fill.papermc.io/
quarkus.rest-client.fabric-api.url=https://meta.fabricmc.net/
quarkus.hibernate-orm.database.generation=update