quarkus.datasource.db-kind=sqlite
quarkus.datasource.jdbc.url=jdbc:sqlite:lapis-mc.db
quarkus.rest-client.paper-api.url=https://fill.papermc.io/
quarkus.rest-client.fabric-api.url=https://meta.fabricmc.net/
quarkus.hibernate-orm.database.generation=update
quarkus.quinoa.build-dir=dist
quarkus.quinoa.package-manager-install.node-version=25.9.0
quarkus.quinoa.package-manager-install.npm-version=11.14.1
quarkus.quinoa.dev-server.port=5173
quarkus.quinoa.dev-server.enabled=true